### ISSUE TITLE
Could not identify valid tracking number

### ISSUE THREAD

**Issue by akaszynski** [sereema/tracking-url#1]
Hello,

It seems the package couldn't identify the tracking number:
```
'92419902118596513000053272'
```
This is a valid USPS tracking number with tracking:
https://tools.usps.com/go/TrackConfirmAction?tRef=fullpage&tLc=2&text28777=&tLabels=92419902118596513000053272%2C

**Comment by kmichel2** [comment]
Hello,

It seems USPS now has 26 digits tracking numbers.
I've added them to the detected patterns and released version 0.0.3 on GitHub and PyPI.

Updating your package should be enough to fix this issue.

Thanks for your bug report.
